spring:

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  redis:
    host:  localhost
    port:  6379
    database: 14
    timeout: 1000

    jedis:
      pool:
        max-wait: 10000
        min-idle:  2
        max-active: 8
        max-idle: 8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
